### ISSUE TITLE
Address Dependabot alerts

### ISSUE THREAD

**Issue by dcamper** [hpcc-systems/HSQL#70]
See https://github.com/hpcc-systems/HSQL/security/dependabot

**Comment by m-kashani** [comment]
![image](https://user-images.githubusercontent.com/3967516/135527618-21c6f0ac-23fd-44d6-aada-1e1f3f6c50da.png)

Everything is up and running.
https://github.com/hpcc-systems/HSQL/commit/14dd762ee600bd6464c0e5592b8cd04a87c3e9d7

**Comment by dcamper** [comment]
Looks good.  We'll close this and wait to see if Dependabot coughs it up again during the next scan.
